export const WEATHER_ACTION_CONST = {
  WEATHER_API_CALL_ACTION: 'WEATHER_API_CALL_ACTION',
  WEATHER_API_CALL_ACTION_SUCCESS: 'WEATHER_API_CALL_ACTION_SUCCESS',
  WEATHER_API_CALL_ACTION_FAILURE: 'WEATHER_API_CALL_ACTION_FAILURE',
}

export const JPH_ACTION_CONST = {
  JPH_API_CALL_ACTION: 'JPH_API_CALL_ACTION',
  JPH_API_CALL_ACTION_SUCCESS: 'JPH_API_CALL_ACTION_SUCCESS',
  JPH_API_CALL_ACTION_FAILURE: 'JPH_API_CALL_ACTION_FAILURE',
}