export const WEATHER_ACTION_CONST = {
  WEATHER_API_CALL_ACTION: 'WEATHER_API_CALL_ACTION',
  WEATHER_API_CALL_ACTION_SUCCESS: 'WEATHER_API_CALL_ACTION_SUCCESS',
  WEATHER_API_CALL_ACTION_FAILURE: 'WEATHER_API_CALL_ACTION_FAILURE'
}